
"use client"
import "./styles/globals.css";
import { usePathname } from "next/navigation";

// COMPONENTS WITH HEADER AND FOOTER
import Header from "@/components/header";
import Footer from "@/components/footer";

// export const metadata = {
//   title: "Create NextJS TailwindCSS App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname=usePathname()
  console.log(pathname);

   // Define an array of valid routes for which Header and Footer should be displayed
   const validRoutes = ["/", "/about", "/service","/products", "/contact"];

  
  return (
    <html lang="en">
      <body>
      {/* S > HEADER */}
      {validRoutes.includes(pathname) && <Header/>}
      {/* E > HEADER */}

      {/* S > CHILDREN MEANS MAIN CONTENT */}
      {children}
      {/* E > CHILDREN MEANS MAIN CONTENT */}

      {/* S > FOOTER */}
      {validRoutes.includes(pathname) && <Footer />}
      {/* E > FOOTER */}
        </body>
    </html>
  );
}
